import postgres from "postgres";
import { DATABASE_SSL, DATABASE_URL } from "./config.js";

export const sql = postgres(DATABASE_URL, {
    max: 5,
    idle_timeout: 20,
    connect_timeout: 15,
    ssl: DATABASE_SSL ? "require" : false
});

export async function initializeDatabase() {
    await sql`
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name VARCHAR(100) NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            reset_token_hash CHAR(64),
            reset_token_expires_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `;

    await sql`
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            total_cents INTEGER NOT NULL CHECK (total_cents >= 0),
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    `;

    await sql`
        CREATE TABLE IF NOT EXISTS order_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
            product_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            price_cents INTEGER NOT NULL CHECK (price_cents >= 0),
            quantity INTEGER NOT NULL CHECK (quantity > 0)
        )
    `;

    await sql`CREATE INDEX IF NOT EXISTS orders_user_id_created_at_idx ON orders (user_id, created_at DESC)`;
    await sql`CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items (order_id)`;
}

export function closeDatabase() {
    return sql.end({ timeout: 5 });
}
